"""Regenerate the Phase 2.3 byte-identity oracle (deterministic).

The oracle (``results/_phase23_baseline/oracle.json``) is the frozen baseline
that proves invariant #1: the contract widening must NOT perturb the legacy
rail / bus KPIs. ``tests/test_composable_service_pipeline.py::
test_byte_identity_against_oracle`` re-runs the 6 frozen runs (bus_only /
multimodal x seeds 1101-1103) and asserts every KPI reproduces bit-for-bit.

This script is the SINGLE SOURCE of the oracle. Run it only when the baseline
LEGITIMATELY changes (e.g. ``MetricsCollector.as_dict`` gains/loses a key, or
the canonical pilot config is intentionally re-tuned). It:

* rebuilds the canonical pilot base config (``make_pilot_base_config`` +
  ``apply_pilot_demand_fleet_profiles`` — the same path the composable tests
  use), and pins ``base_config_sha256`` so a config drift is caught;
* runs the 6 frozen scenarios on the real cached Goseong graph and records the
  FULL ``as_dict()`` (all result keys, not a curated subset) so the oracle
  cannot be silently weakened by dropping keys;
* stamps ``runs_sha256`` = sha256 of the ``runs`` block so a hand-edit to any
  KPI value (the silent-regeneration attack) is detected by the test.

Quasi-real / decision-support only — not an operational plan, forecast, or
calibrated validation. ``final_study_ready`` stays false.

Usage::

    .\\.venv\\Scripts\\python scripts\\generate_phase23_oracle.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

from src.realworld.pilot_experiments import (  # noqa: E402
    _json_sha256,
    apply_pilot_demand_fleet_profiles,
    load_pilot_inputs,
    make_pilot_base_config,
)
from src.scenario import run_scenario  # noqa: E402
from src.policies import StrictPolicy  # noqa: E402

REGION = "data/regions/goseong_mobilization.yaml"
CACHE = "data/cache/goseong_corridor_road.graphml"
ORACLE_PATH = ROOT / "results" / "_phase23_baseline" / "oracle.json"

PARAMS = {"s": 1.0, "p_fail_scale": 0.0, "sigma": 0.75}
RUNS = (
    ("bus_only", 1101),
    ("bus_only", 1102),
    ("bus_only", 1103),
    ("multimodal", 1101),
    ("multimodal", 1102),
    ("multimodal", 1103),
)


def build_oracle() -> dict:
    inputs = load_pilot_inputs(region_path=REGION, cache_path=CACHE)
    # Canonical pilot base config (experiment.time_limit=480, the 8h window).
    # Mirrors tests/test_composable_service_pipeline.py::_base_config exactly.
    base = apply_pilot_demand_fleet_profiles(make_pilot_base_config(inputs.region))[0]

    runs: dict[str, dict] = {}
    for scenario_type, seed in RUNS:
        import copy

        result = run_scenario(
            G=inputs.graph,
            config=copy.deepcopy(base),
            scenario_type=scenario_type,
            policy=StrictPolicy(),
            params=PARAMS,
            seed=seed,
        )
        runs[f"{scenario_type}_s{seed}"] = result

    return {
        "schema_version": 2,
        "description": (
            "Phase 2.3 byte-identity oracle. Generated by "
            "scripts/generate_phase23_oracle.py (single source). The "
            "contract widening must not perturb these legacy rail/bus KPIs. "
            "Regenerate only on a legitimate baseline change."
        ),
        "base_config_sha256": _json_sha256(base),
        "runs_sha256": _json_sha256(runs),
        "runs": runs,
    }


def main() -> None:
    oracle = build_oracle()
    ORACLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    ORACLE_PATH.write_text(
        json.dumps(oracle, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {ORACLE_PATH}")
    print(f"  base_config_sha256 = {oracle['base_config_sha256']}")
    print(f"  runs_sha256        = {oracle['runs_sha256']}")
    print(f"  runs               = {len(oracle['runs'])} x "
          f"{len(next(iter(oracle['runs'].values())))} keys")


if __name__ == "__main__":
    main()
